version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs: 
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:14.16.0
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm test