version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs: 
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:14.16.0
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/project/node_modules
      - run: npm test